### ISSUE TITLE
Lua Error on join for all player

### ISSUE THREAD

**Issue by miniwinz78** [Wolvin-NET/prophuntx#11]
Hi,

All my players have this error on join :

[ERROR] gamemodes/prop_hunt/gamemode/plugins/propmenu/cl_propchoose.lua:14: bad argument #1 to 'JSONToTable' (string expected, got no value)
  1. JSONToTable - [C]:-1
   2. func - gamemodes/prop_hunt/gamemode/plugins/propmenu/cl_propchoose.lua:14
    3. unknown - lua/includes/extensions/net.lua:33

My version come to the workshop https://steamcommunity.com/sharedfiles/filedetails/?id=2176546751

**Comment by Stinggy** [comment]
Make sure you don't have the prop Chooser add-on. It is now built into the game mode and that can cause errors

**Comment by miniwinz78** [comment]
my friends have added to addon folder and workshop on the same time, sorry ^^
