### ISSUE TITLE
Prop not removed when die

### ISSUE THREAD

**Issue by miniwinz78** [Wolvin-NET/prophuntx#12]
I encounter this problem every time, I have no apparent error in the console

**Comment by miniwinz78** [comment]
And have added the pointshop 2 and have this error for every kill : 

[pointshop2-master] addons/pointshop2-master/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:88: attempt to index local 'attacker' (a nil value)
  1. fn - addons/pointshop2-master/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:88
   2. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
    3. unknown - gamemodes/prop_hunt/entities/entities/ph_prop.lua:127

**Comment by Vinzuerio** [comment]
Do you use older version of Pointshop2 before the PH:X Integration fix?
Secondly, if this still presists, there must be an addon that modifies the PlayerDeath or EntityTakeDamage hook event, causes the attacker become nil. Try removing another Prop Hunt gamemodes installed on your server/game if any

**Comment by Vinzuerio** [comment]
ok apparently It's missing `inflictor` argument when Pointshop 2 really needs it

Should be fixed shortly
