### ISSUE TITLE
Dev branch Lua error while opening F1 Menu --> Prop hunt menu

### ISSUE THREAD

**Issue by haeiven** [Wolvin-NET/prophuntx#15]
[Haeiven|2|STEAM_0:1:43774198] Lua Error:

[ERROR] lua/includes/extensions/table.lua:60: bad argument #1 to 'next' (table expected, got nil)
  1. next - [C]:-1
   2. IsEmpty - lua/includes/extensions/table.lua:60
    3. unknown - gamemodes/prop_hunt/gamemode/cl_menutypes.lua:332
     4. CreateVGUIType - gamemodes/prop_hunt/gamemode/cl_menu.lua:118
      5. ShowAdminMenu - gamemodes/prop_hunt/gamemode/cl_menu.lua:519
       6. func - gamemodes/prop_hunt/gamemode/cl_menu.lua:775
        7. unknown - lua/includes/extensions/net.lua:33

**Comment by Vinzuerio** [comment]
Apparently you were using old commit, try using the new commit of https://github.com/Wolvin-NET/prophuntx/commit/a65b671940e815933e5575fe590044b773089d9b

I believe that error comes up with previous old commit, which is why on the line 332 in cl_menutypes.lua was invalid

**Comment by Vinzuerio** [comment]
Use the new branch update to prevent errors. Make sure you made a backup copy from your PH:X if you did some edits.
The new update will be pushed by the latest of June 19th-20th.
