### ISSUE TITLE
Enhancement: teams name

### ISSUE THREAD

**Issue by haeiven** [Wolvin-NET/prophuntx#16]
Hi,

It could be great to be able to rename Teams (display name), so it could be translated.

**Comment by Vinzuerio** [comment]
Should be added shortly, but this uses new function name if you don't mind with it.

**Comment by Vinzuerio** [comment]
Added `PHX:TranslateName( number idTeam, player Ply )` exclusively for Team name translation.
The idTeam must contain number, and player entity. A player entity is only used on server side where you want to send the translation text through serverside to a client. This only works if you use something like PHX:ChatInfo or something. This isn't ideal if you use a hook like on Think or Tick on server side. _You've been warned._

This feature will be added soon on master branch release of PH:X June update.

Extra:
I've also replaced some team text in fretta as well that uses to this function so you don't have to replace the whole codes from it. 
if you're using a custom addon that uses PHX's code, and by trying to use team translation, use this function instead.
