### ISSUE TITLE
How to disable the join screen?

### ISSUE THREAD

**Issue by compieter-gh** [Wolvin-NET/prophuntx#23]
I wanna disable the join screen but have no clue were to find it. 
I already looked into ulx and the config of prophunt. 
And with an file searcher which didnt help.

This is the screen i am talking about. 
![image](https://user-images.githubusercontent.com/34034571/178812223-349d7e65-5cf1-4600-bb91-679494c37e47.png)

**Comment by Vinzuerio** [comment]
This technically have to disable through code but at the moment there's no disable option for splash screens. It's a default behaviour of the fretta.

However I'm gonna to add a convar which disables the splash screen next update.

**Comment by compieter-gh** [comment]
Aah okay thanks.

**Comment by Vinzuerio** [comment]
Added `ph_show_splash_screen` on Dev Branch, If you may to test it out (Make sure you backed up your gamemode before updating), see the new commit here
https://github.com/Wolvin-NET/prophuntx/commit/bd3702861a0eb72807ead5fe47be9d619c5b9198

The master/workshop update should be launched on First/Mid August. Closing this issue after master is released.
