### ISSUE TITLE
Disabled autotaunt issue

### ISSUE THREAD

**Issue by paweldepta** [Wolvin-NET/prophuntx#3]
When I'm disabling auto taunt feature, it's still counting down to negative values and the circle (bottom right) becomes bigger and bigger.

![Preview](https://user-images.githubusercontent.com/16735338/89708770-41b77100-d97a-11ea-86a0-3e0ba8f5cc71.jpg)

**Comment by Vinzuerio** [comment]
It was (Temporary) fixed under dev-branch release, you might have to use the the dev's release for a moment
https://github.com/Wolvin-NET/prophuntx/tree/dev-branch

See if it works

**Comment by paweldepta** [comment]
It works :D
Thanks!

**Comment by Vinzuerio** [comment]
This soon will be improved. will set this issue remain open until the improvement has been fully implemented.

**Comment by Vinzuerio** [comment]
Should be fixed in Revision X2Z.
