### ISSUE TITLE
fgd not working

### ISSUE THREAD

**Issue by xav07theboi** [Wolvin-NET/prophuntx#33]
i added the fgd to hammer but nothin's adding the team spawns am i missing something?

**Comment by Vinzuerio** [comment]
![fgd_test](https://github.com/Wolvin-NET/prophuntx/assets/11814682/265288cf-41c3-4923-b174-52ceaa81d93f)

It appears working on me, testing both garry's mod/half-life 2 fgd + prophuntx fgd

Also it may only works if the fgd is placed in /bin directory, for example:
`C:\Program Files (x86)\Steam\SteamApps\common\GarrysMod\bin\prophuntx.fgd`

Once you copy & pasted the fgd into the bin directory, make sure you have edited your `GameConfig.txt` in the fgd, Add/Edit these line:
```
	. . .
		"Garry's Mod"
		{
			"GameDir"		"C:\Program Files (x86)\Steam\SteamApps\common\GarrysMod\garrysmod"
			"Hammer"
			{
				"GameData0"		"C:\Program Files (x86)\Steam\SteamApps\common\GarrysMod\bin\garrysmod.fgd"
Edit this -->			"GameData1"		"C:\Program Files (x86)\Steam\SteamApps\common\GarrysMod\bin\prophuntx.fgd"
				. . .
```

**_Extra thing to note:_**
- If you use Hammer++, Don't edit the `\bin\GameConfig.txt` but instead `\bin\hammerplusplus\hammerplusplus_gameconfig.txt`
- If you use [HammerAddons](https://github.com/TeamSpen210/HammerAddons) , this will requires FGD edits that supplied from there. I'll provide the additional edits for `HammerAddons` on next update.

**Comment by xav07theboi** [comment]
alright i will see
