### ISSUE TITLE
Hunter spawn without weapons.

### ISSUE THREAD

**Issue by skate6788** [Wolvin-NET/prophuntx#35]
**Hi Wolvin.**
I played with a 2 friends last night on the newest update and we got couple time bug where the hunter spawns without anything. 
From my mind stand it can be related to the automatic team balance swap and the newest function PH_OnHunterLoadOut.

**Comment by skate6788** [comment]
I am using version from workshop so probly master. I am using default settings, so only team balance swap option is enabled.

**Comment by Vinzuerio** [comment]
I think I found a problem, `Player.HasLoadout` stays `true` whenever Team Balance has occured and SetTeam too fast/early, should be fixed.

Btw if that happening again after new revision 17.01.24 update released, Re-open this issue and I will have to investigate more.
