### ISSUE TITLE
Not all models being display in model menu.

### ISSUE THREAD

**Issue by Mattyzz** [Wolvin-NET/prophuntx#7]
Server Parameters:
-Linux Ubuntu LTS 18?
-Ulx, Ulib, Prophuntx(Latest Public 16.08.20) extracted to dedicated server files
-Models mounted via host_workshop_collection argument in launch.sh

When going to the player models only some are being detected. If I were to use a different add-on) such as Enhanced PlayerModel Selector(mounted via workshop collection) then all models are visible that way.

It seemed to work fine when Prophuntx is mounted directly through a workshop collection. I may be doing something wrong that I don't know of. Sorry in advance if this is a non-issue.

Thank you for your work!

**Comment by Vinzuerio** [comment]
Have tried with `ph_use_playermodeltype` and change them to 0 or 1 ?

I'm afraid this must be ConVar issues that not being replicated properly to clients, or the models from the workshop may not provide any Playermodel information so PHX couldn't read them, but Should get this fixed later.

Is there any example workshop player models that doesn't show on the menu?

**Comment by Mattyzz** [comment]
Sorry for the super late reply.

`ph_use_playermodeltype` works just fine.

Models by Maximo such as Azur Lane - Akagi were some that didn't work off the top of my head.
 
An odd anomaly is that when we switched over to PropHuntX; players who had already changed (pre-PropHuntX) their model persisted and they couldn't see it in the menu. 

Thank you again!
