### ISSUE TITLE
Discord Announcement Channel

### ISSUE THREAD

**Issue by LogicPlague** [Wolvin-NET/prophuntx#9]
I have suggestion not for the game mode it self, but for the discord. You should make the a community, if that is a requirement for my main suggestion, and turn the announcement channel setting for the announcement channel. This will allow people to follow the channel it self and they would be able to get announcements about PH in there discord servers.

**Comment by Vinzuerio** [comment]
There was Discord announcement, which you can join here:
https://discord.gg/avaTPM7
